import { useDocumentTitle, useScrollTop } from "hooks";
import React from "react";

function TermsAndConditions() {
  useDocumentTitle("Terms And Conditions | Prime Games");
  useScrollTop();

  return (
    <main className="content">
      <div>
        <h3>Terms & Conditions</h3>
        <p>
          This document is an electronic record in terms of Information
          Technology Act, 2000 and rules thereunder, as applicable and the
          amended provisions pertaining to electronic records in various
          statutes, as amended from time to time by the Information Technology
          Act, 2000. This electronic record is generated by a computer system
          and does not require any physical or digital signatures.
        </p>
        <p>
          This document is published in accordance with the provisions of Rule
          3(1) of the Information Technology (Intermediaries guidelines) Rules,
          2011 that requires publishing of the rules and regulations, privacy
          policy and Terms of Use for access or usage of www.alliswell.app/
          website and its mobile applications.
        </p>
        <ol type="1">
          <li>
            GENERAL
            <p>
              alliswell.app/an internet based portal and “All Is Well”, a mobile
              application, (hereinafter together be referred to as “Website") is
              run, operated and maintained by All is Well Solutions Private
              Limited (hereinafter to be referred as “Company” or “We” or “Our”
              or “Us”), a company duly incorporated under the provisions of the
              Companies Act, 2013.
            </p>
            <p>
              Use of the Website is offered to You, subject to acceptance of all
              the terms, conditions and notices contained in these Terms
              including applicable policies which are incorporated herein by
              reference, along with any amendments / modifications made time to
              time by Company at its sole discretion and posted on the Website,
              including by way of imposing an additional charge for access to or
              use of a service(s).
            </p>
            <p>
              For the purpose of these Terms of Use, wherever the context so
              requires "You" or "User" shall mean any natural or legal person
              who has agreed to become a buyer on the Website by providing
              Account Information (defined below) while registering on the
              Website as a registered User using the computer systems.
            </p>
            <p>
              Company shall not be required to notify You, whether as a
              registered user or not, of any changes made to the Terms and
              Conditions ("Terms"). The revised Terms shall be made available on
              the Website. Your use of the Website and the Services is subject
              to the most current version of the Terms made available on the
              Website, at the time of such use. You are requested to regularly
              visit the Website to view the most current Terms. It shall be Your
              responsibility to check the Terms periodically for changes.
              Company may require You to provide Your consent to the updated
              Terms in a specified manner prior to any further use of the
              Website and the Services, provided on the Website. If no such
              separate consent is sought, Your continued use of the Website,
              following changes to the Terms, will constitute your express
              acceptance of those changes.
            </p>
            <p>
              By (i) using this Website or any facility or service provided by
              this Website in any way; or (ii) merely by browsing the Website,
              You agree that you have read, understood and agreed to be bound
              by, including without limitation, by these Terms, the Website's
              Privacy Policy. and such other rules, guidelines, policies, terms
              and conditions as are relevant under the applicable law(s) in
              India and other jurisdictions, for the purposes of accessing,
              browsing or transacting on the Website, or availing any of the
              Services, and such rules, guidelines, policies, terms and
              conditions shall be deemed to be incorporated into, and considered
              as part and parcel of these Terms of Use.
            </p>
            <p>
              Company shall not be liable to deliver any Products purchased by
              You for delivery, in locations outside India.
            </p>
            <p>
              The User agrees to use the service to authorise an individual and
              get the products from the third party on his/her behalf.
            </p>
          </li>
          <li>
            PRODUCTS AND SERVICES
            <p>
              The Website is a platform that facilitates, as an intermediary,
              the online requisition by the user for purchase of medicines and
              wellness / health related products and services offered by
              Company's various registered third-party/ies (third-parties shall
              for the purpose of this Terms, include without limitation, third
              party retail pharmacies, third-party labs et al) ("Products and
              Services"). The sale & purchase / transaction between the
              registered third-parties and You, of Products and Services,
              facilitated by the requisition placed by You on the Website shall
              be governed by these Terms. Company is not and cannot be a party
              to or save as except as may be provided in these Terms of Use,
              control in any manner, any transaction between You and the
              third-parties.
            </p>
            <p>
              Company further reserves the right to change or modify these Terms
              of Use or any policy or guidelines of the Website including the
              Privacy Policy, at any time and in its sole discretion. Any
              changes or modifications made will be effective immediately upon
              posting the revisions on the Website and You waive any right You
              may have to receive specific notice of such changes or
              modifications. Your continued use of the Website will confirm Your
              acceptance of such changes or modifications.
            </p>
            <h3>Technology Platform for Pharmaceutical Products –</h3>
            <p>
              Company facilitates the purchase of drugs and other pharmaceutical
              products, nutraceutical products and services (which shall also
              include Over The Counter (OTC) and wellness products) offered by
              third-party retail pharmacies (“Retail Pharmacies”). The Company
              and the Website merely provide hosting and technology intermediary
              services to You and persons browsing/ visiting the Website. All
              items offered for sale on the Website, and the content made
              available by the Retail Pharmacies, are third party user generated
              contents and third party products. The Company has no control over
              such third party user generated contents and/ Pharmaceutical Goods
              and Services and does not originate or initiate the transmission,
              or select the sender/recipient of the transmission, or the
              information contained in such transmission. The authenticity and
              genuineness of the Pharmaceutical Goods and Services made
              available by the Retail Pharmacies through the Website shall be
              the sole responsibility of the Retail Pharmacies. The Company
              shall have no liability with respect to the authenticity of the
              Pharmaceutical Goods and Services being facilitated through the
              Website. The Company does not take any representation or warranty
              as to legal title of the Pharmaceutical Goods and Services offered
              for sale by the Retail Pharmacies on the Website. The right,
              title, claim or interest in the products sold through the Website
              shall not vest with the Company and the Company shall not have any
              obligations or liabilities in respect of any transactions on the
              Website.
            </p>
            <p>
              The Company is not responsible for delayed, non-performance or
              breach of contract entered into between You and the third-party
              for purchase and sale of goods or services offered by such Retail
              Pharmacies on the Website; The Company gives no guarantee that the
              concerned Retail Pharmacies will perform any transaction concluded
              on the Website. The Company is not responsible for the
              Pharmaceutical Goods and Services which are out of stock, back
              ordered or otherwise unavailable, but were shown as available on
              the Website at the time of placement of order by You.
            </p>
            <p>
              Content: You agree and acknowledge that the respective third-party
              pharmacies are exhibiting Third Party Content which includes
              catalogue of drugs/ pharmaceutical products or services, and
              information in relation to such drugs/ pharmaceutical products or
              services, on the Website. The content available on the Website,
              including without limitation, text, copy, audio, video graphics
              etc is for general information purposes only and does not
              constitute either an advertisement or promotion of any drug being
              offered for sale by the third-party pharmacies on the Website or
              any professional medical advice, diagnosis, treatment or
              recommendation of any kind. Further, the Company shall not be
              responsible for ensuring that the content made available are not
              misleading and describe the actual condition of the Pharmaceutical
              Goods and Services. Also, You acknowledge and understand that the
              Company provides no warranty or representation with respect to the
              authenticity of the information provided on the Website and You
              must do Your own check.
            </p>
            <p>
              The Company shall not be, in any event, held responsible or liable
              for any damages arising out of such content by third-parties.
            </p>
            <h3>Prescription Drugs- </h3>
            <p>
              In order to purchase drugs and pharmaceutical products that
              requires a valid prescription, You are required to upload a
              scanned copy of the valid prescription on the Website. Third-
              Party Pharmacies will verify the prescription forwarded by You and
              in case of any discrepancy observed by the third-party pharmacies,
              the order will be cancelled by the third-party pharmacies
              immediately. You are also required to make the original
              prescription available at the time of receipt of delivery of the
              order. You shall also allow the delivery agent to stamp the
              original prescription at the time of medicine delivery, failing
              which medicines will not be delivered.
            </p>
            <h3>Substitution of Prescribed Drugs- </h3>
            <p>
              You acknowledge and accept that the order for a substitute of a
              Prescription Drug would only be processed if the medical expert/
              doctor has himself/ herself permitted for any other equivalent
              generic drug to be dispensed in place of the Prescription Drug in
              the prescription or if the prescription solely lists the salt
              names instead of a specific brand name. You further acknowledge
              and accept that, in the absence of the above, the concerned Third
              Party Pharmacy would not dispense a substitute drug in place of
              the Prescription Drug.
            </p>
            <h3>Invitation to offer for sale- </h3>
            <p>
              - The listing of drugs and other pharmaceutical products on the
              Website by the Third Party Pharmacies is merely an ‘invitation to
              an offer for sale’ and not an ‘offer for sale’. The placement of
              an order by You shall constitute an offer by You to enter into an
              agreement with the Third Party Pharmacies (“Offer”). Post the
              Offer from the Third Party Pharmacies, the Company shall send an
              email to You with the information on the Offer along with the
              details of the concerned Third Party Pharmacy(s) who may undertake
              the sale, and such an email shall not be considered as an
              acceptance of the Offer. The acceptance of the Offer would only be
              undertaken by the Third Party Pharmacy(s) after the validation/
              verification of the prescription by such Third Party Pharmacy (in
              case of Prescription Drugs) and the ascertainment of the available
              stock in the relevant Third Party Pharmacy(s) (in the case of
              prescription as well as other drugs/ pharmaceutical products), by
              way of a confirmatory email to be sent to You.
            </p>
            <p>
              It is hereby clarified that any reference of the term ‘offer/
              offered for sale by the Retail Pharmacies’, as appearing in these
              Terms of Use, shall be construed solely as an ‘invitation to offer
              for sale’ by any such Retail Pharmacies.
            </p>
            <h3>Transfer of Property and Completion of Sale- </h3>
            <p>
              concerned Retail Pharmacies (being the brick and mortar pharmacy),
              the Pharmaceutical Drugs and Services would be dispensed at the
              pharmacy, in accordance with the terms of the order placed by You.
              Such dispensation shall also take place under the direct/ personal
              supervision of the pharmacist of the Retail Pharmacies, wherever
              required under the applicable law(s).
            </p>
            <p>
              You agree and acknowledge that the property and title in the
              Pharmaceutical Drugs and Services ordered by You shall stand
              immediately transferred to You upon the dispensation of
              Pharmaceutical Drugs and Services and the raising of the invoice
              at the concerned Retail Pharmacies. Accordingly, the sale of
              Pharmaceutical Drugs and Services is concluded at the concerned
              Retail Pharmacies itself.
            </p>
            <p>
              The invoice in relation to the Pharmaceutical Drugs and Services,
              that are required to be delivered to You shall be issued by the
              concerned Retail Pharmacies (being the brick and mortar pharmacy)
              which is to process and satisfy the order for such Pharmaceutical
              Drugs and Services.
            </p>
            <h3>Drugs Delivery- </h3>
            <p>
              The Pharmaceutical Drugs and Services shall be delivered by the
              Retail Pharmacies or independent contractors. You accept and
              acknowledges that the courier/ delivery personnel, engaged by the
              Retail Pharmacies or the Company, shall be User Agent of the
              delivery of the Pharmaceutical Drugs and Services from the
              concerned Retail Pharmacies to the address notified by You, with
              no control over the Pharmaceutical Drugs and Services and no
              additional obligation apart from standard delivery obligations and
              duty of care.
            </p>
          </li>
          <li>
            ELIGIBILITY OF USE
            <p>
              Use of the Website is available only to persons who can form
              legally binding contracts under Indian Contract Act, 1872. Persons
              who are "incompetent to contract" within the meaning of the Indian
              Contract Act, 1872 including without limitation, minors,
              un-discharged insolvents etc. are not eligible to use the Website.
              The Products shall also not available to any Users suspended or
              removed from the company’s system for any reason whatsoever. If
              You do not conform to the above qualification, You will not be
              permitted to put a requisition for the Products through the
              Website. By accessing and using this Website, You represent that
              You are of legal age to form a binding contract and are not a
              person barred from receiving services under the laws as applicable
              in India. Notwithstanding the foregoing, if You are below the age
              of eighteen (18) years, You may avail the services provided by the
              Website, through Your legal guardian in accordance with the
              applicable laws.
            </p>
            <p>
              Company reserves the right to terminate your membership and / or
              refuse to provide you with access to the Website if it is brought
              to Company’s notice or if it is discovered that you are under the
              age of 18 years.
            </p>
            <p>
              Company reserves the right to refuse access to use the services
              offered at the Website to new Users or to terminate access granted
              to existing Users at any time without according any reasons for
              doing so and You shall have no right to object to the same. You
              shall not have more than one active Account on the Website.
              Additionally, You are prohibited from selling, trading, or
              otherwise transferring Your Account to another party.
            </p>
          </li>
          <li>
            USER ACCOUNT, PASSWORD AND SECURITY
            <p>
              Company shall enable You to make the requisition of Products and
              Services available to You through the Website, only if You have
              provided Company certain required User information, including
              without limitation, name; user ID; email address; address; gender;
              age; phone number; password; valid finance account information;
              and other details and created an account ("Account") through
              Company ID and password or other log-in ID and password, which can
              include a facebook, gmail, yahoo ID or any other valid email ID
              (collectively, the "Account Information") . The transaction and
              delivery of the Products by the registered merchants/vendors may
              also be subject to procedures for use of the Website, Terms,
              uploaded guidelines, rules, additional terms of service, or other
              disclaimer & notices, if any ("Additional Terms"). If there is any
              conflict between the Terms and the Additional Terms, the
              Additional Terms shall take precedence in relation to that
              service.
            </p>
            <p>
              The Website requires You to register as a User by creating an
              Account in order to avail of the services provided by the Website.
              You will be responsible for maintaining the confidentiality of the
              Account Information, and are fully responsible for all activities
              that occur under Your Account. You agree to (a) immediately notify
              Company of any unauthorized use of Your Account or Account
              Information or any other breach of security, non-compliance with
              the TP Guidelines and (b) ensure that You exit / log out from Your
              Account at the end of each session. Company cannot and will not be
              liable for any loss or damage arising from Your failure to comply
              with this Paragraph 4. You may be held liable for losses incurred
              by Company or any other User of or visitor to the Website due to
              authorized or unauthorized use of Your Account as a result of Your
              failure in keeping Your Account Information secure and
              confidential or otherwise. The Website also allows / shall allow
              restricted access to the Website for unregistered Users.
            </p>
            <p>
              You shall ensure that the Account Information provided by You in
              the Website's registration form is true, complete, accurate and
              up-to-date. Use of another User's Account Information for availing
              the services offered by Company is expressly prohibited.
            </p>
            <p>
              If You provide any information that is untrue, inaccurate, not
              current or incomplete (or becomes untrue, inaccurate, not current
              or incomplete), or Company has reasonable grounds to suspect that
              such information is untrue, inaccurate, not current or incomplete,
              Company has the right to suspend or terminate Your Account and
              refuse any and all current or future use of the Website by You.
            </p>
            <p>
              You confirm that you are the authorised holder of the credit card
              or the original account holder used in the transactions he/she
              makes using the Website. Company will not be responsible for any
              financial loss, inconvenience or mental agony resulting from
              misuse of the Your ID/password/credit card number/account details
              number for using the Website.
            </p>
            <p>
              The Website uses temporary cookies to store certain data (that is
              not sensitive personal data or information) that is used by
              Company for the technical administration of the Website, research
              and development, and for User administration. In the course of
              serving advertisements or optimizing services to You, Company may
              allow authorized third parties to place or recognize a unique
              cookie on the Your browser. Company does not store personally
              identifiable information in the cookies.
            </p>
          </li>
          <li>
            PRICING INFORMATION AND PAYMENT
            <p>
              Company strives to provide You with the best prices possible on
              the Products You require from the Website. The pricing details for
              purchase of Products from the Website are detailed under these
              Terms.
            </p>
            <p>Further:</p>
            <ol type="1">
              <li>
                All commercial terms such as price, delivery, dispatch of
                Products and/or services are as per principal to principal
                bipartite contractual obligations between User and the third
                parties.
              </li>
              <li>
                Your relationship with Company is on a principal to principal
                basis and by accepting these Terms of Use You agree that Company
                is an independent contractor for all purposes, and does not have
                control of or liability for the products or services that are
                listed/ offered on Company's Website. Company does not guarantee
                the identity of any third-parties nor does it ensure that a User
                or a third party will complete a transaction.
              </li>
              <li>
                You, as a User, understand that upon initiating a requisition on
                the Website, You are entering into a legally binding and
                enforceable contract with the third party to purchase the
                Products and /or Services from the third party on a cash on
                delivery basis or such other mode as may be specified by
                Company.
              </li>
              <li>
                You, as a User, shall hand over a copy of the prescription, at
                the time of delivery, for the delivery of Products which as per
                law requires a valid prescription signed by a medical
                practitioner. You acknowledge that delivery of such Products
                shall be made only if the third party or its agent/employee is
                satisfied that the prescription is in compliance with applicable
                norms.
              </li>
              <li>
                You, as a User, shall electronically notify Company using the
                appropriate Company’s Website features immediately upon Delivery
                or non-Delivery within the time period as provided in these
                Terms of Use. Non-notification by You of delivery or
                non-delivery within the time period specified in the these Terms
                of Use shall be construed as a deemed delivery in respect of
                that particular order.
              </li>
              <li>
                You, as a User, shall be entitled to claim a refund in
                accordance with the Refund and Return Policy of the Company.
              </li>
              <li>
                Refund shall be made in Indian Rupees only and shall be
                equivalent wholly or a part of the Transaction Price received in
                Indian Rupees.
              </li>
              <li>
                Refund shall be subject to User complying with these Terms of
                Use.
              </li>
              <li>
                Company reserves the right to refuse to process
                orders/requisitions from Users with a prior history of
                questionable charges including without limitation breach of any
                agreements by User with Company or breach of any policy.
              </li>
              <li>
                The User and third-party acknowledge that Company will not be
                liable for any damages, interests or claims etc. resulting from
                not processing a transaction/transaction price or any delay in
                processing a transaction/transaction price which is beyond
                control of Company.
              </li>
              <li>
                You acknowledge that Company is a mere facilitator and does not
                fall within the purview of the Food Safety and Standards Act,
                2006 and the rules framed thereunder.
              </li>
              <li>
                You acknowledge that Company is a mere facilitator and does not
                fall within the purview of the Drugs and Cosmetics Act, 1940 and
                the rules framed thereunder.
              </li>
              <li>
                You acknowledge that Company is a mere facilitator/intermediary
                and does not fall within the purview of the National Medical
                Commission Act, 2019, and the rules and regulations framed
                thereunder.
              </li>
              <li>
                {" "}
                The User also agrees to pay a nominal fee for the same.
                <i>
                  In order to process the payments for Your orders, the Company
                  might require details of Your bank account, credit card number
                  etc. The online fee payments made by You are processed with
                  the support and services of the banks/payment gateways/payment
                  aggregators/ third parties and the Company and/or Seller is
                  not responsible for any loss or damage caused to User/ Retail
                  Pharmacies/ third party service providers during this process
                  as these banks/payment gateways/payment aggregators/ third
                  parties are beyond the control of the Company. There are no
                  applicable payment charges levied on any transactions. Click
                  here to see the list of our available payment methods and
                  payment partners.
                </i>
                <i>
                  Subscription Fee- Any subscription fees for the Services
                  charged by the Company, could be paid online through the
                  facility made available on the Website. Such online fee
                  payments are also processed with the support and services of
                  the banks/payment gateways/payment aggregators/ third parties
                  and the Company and/or Seller is not responsible for any loss
                  or damage caused to User/ Retail Pharmacies/ third party
                  service providers during this process as these banks/payment
                  gateways/payment aggregators/ third parties are beyond the
                  control of the Company and/or Seller.
                </i>
                <i>
                  Taxes- Each User / third party service provider is solely
                  responsible for payment of all taxes, legal compliances,
                  statutory registrations and reporting. The Company and/or
                  Seller shall in no way be responsible for any of the taxes
                  except for its own taxes. Further please note that all fees
                  are exclusive of applicable taxes.
                </i>
                <i>
                  Security Measures- The payment made for every transaction is
                  done through API integration. Moreover, You may also check Our
                  Privacy Policy to understand how the Company uses the
                  confidential information provided by Users.
                </i>
                <i>
                  The Company reserves the right to modify the fee structure by
                  providing on the Website which shall be considered as valid
                  and agreed communication. The Company and/or Seller shall not
                  be responsible if some purchase is not registered or is lost
                  due to any network issues/problems such as breakdown of
                  machinery, unclear/ disruption in the network or non-receipt
                  of payment from banks/payment gateways/payment
                  aggregators/third parties and/or the cost(s) charged by the
                  network operator(s). However, the Company shall work towards
                  the best interest of the User.
                </i>
                <i>
                  Dispute- Any dispute in connection to the third-parties
                  services shall be settled between the Users and the respective
                  third parties, including without limitations, banks/payment
                  gateways/payment aggregators/network operators without
                  involving the Company and/or Seller
                </i>
              </li>
            </ol>
          </li>
          <li>
            USER OBLIGATIONS
            <p>
              Subject to compliance with these Terms, Company grants You a
              personal, non-exclusive, non-transferable, limited privilege to
              access and use this Website and the Services provided herein.
            </p>
            <p>
              You agree to use the Services, Website and the materials provided
              therein only for purposes that are permitted by: (a) the Terms;
              and (b) any applicable law, regulation or generally accepted
              practices or guidelines in the relevant jurisdictions.
            </p>
            <p>
              You agree to adhere to all limitations on dissemination, use and
              reproduction of any materials (such as the Product catalogues)
              that You access on the Website in accordance with Paragraph 7
              below.
            </p>
            <p>
              You agree not to access (or attempt to access) the Website and the
              materials or services by any means other than through the
              interface that is provided by Company. You shall not use any
              deep-link, robot, spider or other automatic device, program,
              algorithm or methodology, or any similar or equivalent manual
              process, to access, acquire, copy or monitor any portion of the
              Website or Content (as defined below), or in any way reproduce or
              circumvent the navigational structure or presentation of the
              Website, materials or any Content, to obtain or attempt to obtain
              any materials, documents or information through any means not
              specifically made available through the Website. You acknowledge
              and agree that by accessing or using the Website or Services, You
              may be exposed to content from other users that You may consider
              offensive, indecent or otherwise objectionable. Company disclaims
              all liabilities arising in relation to such offensive content on
              the Website. Further, You may report such offensive content in the
              manner prescribed herein.
            </p>
            <p>
              If the Website allows You to post and upload any material on the
              Website, You hereby undertake to ensure that such material is not
              offensive and in accordance with applicable laws. Further, You
              undertake not to:
              <ul>
                <li>
                  Defame, abuse, harass, threaten or otherwise violate the legal
                  rights of others;
                </li>
                <li>
                  Impersonate any person or entity, or falsely state or
                  otherwise misrepresent Your affiliation with a person or
                  entity;
                </li>

                <li>
                  Publish, post, upload, distribute or disseminate any
                  inappropriate, profane, defamatory, infringing, obscene,
                  indecent or unlawful topic, name, material or information
                  through any bookmark, tag or keyword;
                </li>
                <li>
                  Upload files that contain software or other material protected
                  by applicable intellectual property laws unless You own or
                  control the rights thereto or have received all necessary
                  consents;
                </li>
                <li>
                  Upload or distribute files that contain viruses, corrupted
                  files, or any other similar software or programs that may
                  damage the operation of the Website or another's computer;
                </li>
                <li>
                  Engage in any activity that interferes with or disrupts access
                  to the Website or the services (or the servers and networks
                  which are connected to the Website);
                </li>
                <li>
                  Attempt to gain unauthorized access to any portion or feature
                  of the Website, any other systems or networks connected to the
                  Website, to any Company server, or to any of the services
                  offered on or through the Website, by hacking, password mining
                  or any other illegitimate means;
                </li>
                <li>
                  Probe, scan or test the vulnerability of the Website or any
                  network connected to the Website, nor breach the security or
                  authentication measures on the Website or any network
                  connected to the Website. You may not reverse look-up, trace
                  or seek to trace any information on any other user, of or
                  visitor to, the Website, or any other customer of Company,
                  including any Company Account not owned by You, to its source,
                  or exploit the Website or service or information made
                  available or offered by or through the Website, in any way
                  whether or not the purpose is to reveal any information,
                  including but not limited to personal identification
                  information, other than Your own information, as provided for
                  by the Website;
                </li>
                <li>
                  Disrupt or interfere with the security of, or otherwise cause
                  harm to, the Website, systems resources, accounts, passwords,
                  servers or networks connected to or accessible through the
                  Websites or any affiliated or linked sites;
                </li>
                <li>
                  Collect or store data about other users in connection with the
                  prohibited conduct and activities set forth in this Paragraph.
                </li>
                <li>
                  Use any device or software to interfere or attempt to
                  interfere with the proper working of the Website or any
                  transaction being conducted on the Website, or with any other
                  person's use of the Website;
                </li>
                <li>
                  Use the Website or any material or Content for any purpose
                  that is unlawful or prohibited by these Terms, or to solicit
                  the performance of any illegal activity or other activity
                  which infringes the rights of Company or other third parties;
                </li>
                <li>
                  Conduct or forward surveys, contests, pyramid schemes or chain
                  letters;
                </li>
                <li>
                  Download any file posted by another user of a service that you
                  know, or reasonably should know, cannot be legally distributed
                  in such manner;
                </li>
                <li>
                  Falsify or delete any author attributions, legal or other
                  proper notices or proprietary designations or labels of the
                  origin or source of software or other material contained in a
                  file that is uploaded;
                </li>
                <li>
                  Violate any code of conduct or other guidelines, which may be
                  applicable for or to any particular Service;
                </li>
                <li>
                  Violate any applicable laws or regulations for the time being
                  in force within or outside India;
                </li>
                <li>
                  Violate the Terms, including but not limited to any applicable
                  Additional Terms of the Website contained herein or elsewhere;
                  and
                </li>
                <li>
                  Reverse engineer, modify, copy, distribute, transmit, display,
                  perform, reproduce, publish, license, create derivative works
                  from, transfer, or sell any information or software obtained
                  from the Website.
                </li>
              </ul>
            </p>
            <p>
              Company has no obligation to monitor such communications by You.
              However, Company reserves the right to review materials posted by
              You and to remove any materials in its sole discretion. Company
              reserves the right to terminate the User's access to any or all of
              such communication services provided by Company at any time,
              without notice for any reason whatsoever.
            </p>
            <p>
              Company reserves the right at all times to disclose any
              information as is necessary to satisfy or comply with any
              applicable law, regulation, legal process or governmental request,
              or to edit, refuse to post or to remove any information or
              materials, in whole or in part, in Company's sole discretion.
            </p>
            <p>
              Company does not control or endorse the content, messages or
              information found in any communication service and, therefore,
              Company specifically disclaims any liability or responsibility
              whatsoever with regard to the communication services and any
              actions resulting from the user's participation in any
              communication service. You agree that You are solely responsible
              to Company and to any third party for any breach of Your
              obligations under the Terms and for the consequences (including
              any loss or damage which company or its affiliates or its vendors
              may suffer) for any such breach.
            </p>
            <p>
              You agree and acknowledge that Company is not the third party
              owner of the Products and Company shall in no manner be deemed to
              be the third party owner of the Products on this Website. Company
              is only facilitating purchase of the Products by You from the
              third parties by providing the services to You.
            </p>
            <p>
              You agree that Company may, at any time, modify or discontinue all
              or part of the Website, charge, modify or waive fees required to
              use the Website, or offer opportunities to some or all Website
              Users.
            </p>
            <p>
              You agree that the Website shall not be used for illegal purposes.
              The Information and Services shall not be used for any illegal
              purpose. You shall not access our networks, computers, or the
              Information and Services in any manner that could damage, disable,
              overburden, or impair them, or interfere with any other person's
              use and enjoyment. You shall not attempt to gain unauthorized
              access to any Information or Services, other accounts, computer
              systems, or networks connected with the Website, the Information,
              or Services. Such unauthorized access includes, but is not limited
              to, using another person’s login credentials to access his or her
              Company profile/ account. Any attempt by any individual or entity
              to solicit login information of any other user or Medical Expert
              or to access any such account is an express and direct violation
              of these Terms of Use and of applicable law(s), including relevant
              privacy and security laws and laws prohibiting unfair or unethical
              business practices.
            </p>
            <p>
              You agree and acknowledge that the exchanges between the third
              party registered medical practitioners and You over telephone and
              the e-prescription would be accessible to the Company for the
              purposes of monitoring the quality of the consultation. The
              consultation provided by the third-party registered medical
              practitioner shall be done vide a secured recorded line.
            </p>
          </li>
          <li>
            USE OF MATERIALS
            <p>
              Except as expressly indicated to the contrary in any applicable
              Additional Terms, Company hereby grants You a personal,
              non-exclusive, freely revocable (upon notice from Company),
              non-transferable access to view, download and print product
              catalogues or any other materials available on the Website,
              subject to the following condition:
            </p>
            <ul>
              <li>
                You may access and use the materials solely for personal,
                informational, and internal purposes, in accordance with the
                Terms; You may not modify or alter Product catalogues or any
                other materials available on the Website;
              </li>
              <li>
                You may not distribute or sell, rent, lease, license or
                otherwise make the Product catalogues or any other materials
                available on the Website available to others; and
              </li>
              <li>
                You may not remove any text, copyright or other proprietary
                notices contained in the Product catalogues or any other
                materials available on the Website.
              </li>
            </ul>
            <p>
              The rights granted to You in the Product catalogues or any other
              materials as specified above are not applicable to the design,
              layout or look and feel of the Website. Such elements of the
              Website are protected by intellectual property rights and may not
              be copied or imitated in whole or in part. The Product catalogues
              or any other materials available on the Website shall not be
              copied or retransmitted unless expressly permitted by Company.
            </p>
            <p>
              Any software that is available on the Website is the property of
              Company or its third parties. You may not use, download or install
              any software available at the Website, unless otherwise expressly
              permitted by these Terms or by the express written permission of
              Company.
            </p>
            <p>
              Any purchase of the merchandise or Services from the Website will
              be strictly for personal use of the User. The User hereby
              expressly agrees that any merchandize or Services purchased by the
              User will not be sold, resold, bartered or in any way be used for
              any commercial purposes or for profit. The User hereby
              acknowledges that the Services or merchandize purchased are not
              transferrable to any third party for profit.
            </p>
          </li>
          <li>
            USAGE CONDUCT
            <p>
              You shall solely be responsible for maintaining the necessary
              computer equipments and internet connections that may be required
              to access, use and transact on the Website. You are also under an
              obligation to use this Website for reasonable and lawful purposes
              only, and shall not indulge in any activity that is not envisaged
              through the Website. You shall use this Website, and any voucher/
              coupons purchased through it, for personal, non-commercial use
              only and shall not re-sell the same to any other person. Once you
              subscribe with All Is Well, you shall use the prescription
              exclusively to purchase medicines via All Is Well and shall not
              use the same prescription to fulfill the medicine requirement from
              other retailers until the medicines are not supplied for any
              reason via All Is Well partner third parties.
            </p>
          </li>
          <li>
            INTELLECTUAL PROPERTY RIGHTS
            <p>
              The Website, the processes, and their selection and arrangement,
              including but not limited to all text, graphics, user interfaces,
              visual interfaces, sounds and music (if any), artwork and computer
              code (collectively, the "Content") on the Website is owned and
              controlled by Company and the design, structure, selection,
              coordination, expression, look and feel and arrangement of such
              Content is protected by copyright, patent and trademark laws, and
              various other intellectual property rights.
            </p>
            <p>
              The trademarks, logos and service marks displayed on the Website
              ("Marks") are the property of Company or their third parties or
              respective third parties. You are not permitted to use the Marks
              without the prior consent of Company, the relevant third parties
              that may own the Marks.
            </p>
            <p>
              Unless otherwise indicated or anything contained to the contrary
              or any proprietary material owned by a third party and so
              expressly mentioned, Company owns all intellectual property rights
              to and into the trademark “www.alliswell.app”, and the Website,
              including, without limitation, any and all rights, title and
              interest in and to copyright, related rights, patents, utility
              models, designs, know-how, trade secrets and inventions (patent
              pending), goodwill, source code, meta tags, databases, text,
              content, graphics, icons, and hyperlinks.
            </p>
            <p>
              Except as expressly provided herein, You acknowledge and agree
              that You shall not copy, republish, post, display, translate,
              transmit, reproduce or distribute any Content through any medium
              without obtaining the necessary authorization from Company or
              third party owner of such Content.
            </p>
          </li>
          <li>
            RETURN, REFUND, CANCELLATION AND SHIPPING CHARGES:
            <p>
              We offer return and refund on the products and Services ordered by
              You on the Website which are subject to further terms and
              conditions as detailed in the return, refund, cancellation and
              shipping charges policy . The Return and Privacy Policy forms an
              integral part of these Terms of Use and the Users are requested to
              carefully read the same.
            </p>
          </li>
          <li>
            DISCLAIMER OF WARRANTIES AND LIABILITIES
            <p>
              You expressly understand and agree that, to the maximum extent
              permitted by applicable law the website, services and other
              materials are provided by Company on an "as is" basis without
              warranty of any kind, express, implied, statutory or otherwise,
              including the implied warranties of title, non-infringement,
              merchantability or fitness for a particular purpose. Without
              limiting the foregoing, Company makes no warranty that (i) the
              Website or the services will meet your requirements or your use of
              the Website or the services will be uninterrupted, timely, secure
              or error-free; (ii) the results that may be obtained from the use
              of the Website, services or materials will be effective, accurate
              or reliable; (iii) the quality of the Website, services or other
              materials will meet your expectations; or that (iv) any errors or
              defects in the Website, services or other materials will be
              corrected. No advice or information, whether oral or written,
              obtained by you from Company or through or from use of the
              services shall create any warranty not expressly stated in the
              terms.
            </p>
            <p>
              To the maximum extent permitted by applicable law, Company will
              have no liability related to user content arising under
              intellectual property rights, libel, privacy, publicity, obscenity
              or other laws. Company also disclaims all liability with respect
              to the misuse, loss, modification or unavailability of any user
              content.
            </p>
            <p>
              Company will not be liable for any loss that you may incur as a
              consequence of unauthorized use of Your Account or Account
              information in connection with the Website or any services or
              materials, either with or without your knowledge. Company has
              endeavored to ensure that all the information on the Website is
              correct, but Company neither warrants nor makes any
              representations regarding the quality, accuracy or completeness of
              any data, information, product or service. Company shall not be
              responsible for the delay or inability to use the Website or
              related functionalities, the provision of or failure to provide
              functionalities, or for any information, software, products,
              functionalities and related graphics obtained through the Website,
              or otherwise arising out of the use of the Website, whether based
              on contract, tort, negligence, strict liability or otherwise.
              Further, Company shall not be held responsible for
              non-availability of the Website during periodic maintenance
              operations or any unplanned suspension of access to the Website
              that may occur due to technical reasons or for any reason beyond
              Company's control. The User understands and agrees that any
              material or data downloaded or otherwise obtained through the
              Website, is done entirely at their own discretion and risk and
              they will be solely responsible for any damage to their computer
              systems or loss of data that results from the download of such
              material or data. Company is not responsible for any typographical
              error leading to an invalid coupon. Company accepts no liability
              for any errors or omissions, with respect to any information
              provided to you whether on behalf of itself or third parties.
              Company shall not be liable for any third party product or
              services. the advertisement available on e-mail or website with
              respect to the third party website or the Products are for
              information purpose only.
            </p>
            <p>
              You expressly agree that Your use of the Website is at Your risk.
            </p>
          </li>
          <li>
            INDEMNIFICATION AND LIMITATION OF LIABILITY
            <p>
              You agree to indemnify, defend and hold harmless Company including
              but not limited to its affiliates, vendors, representatives,
              directors, agents and employees from and against any and all
              losses, liabilities, claims, damages, demands, costs and expenses
              (including legal fees and disbursements in connection therewith
              and interest chargeable thereon) asserted against or incurred by
              Company that arise out of, result from, or may be payable by
              virtue of, any breach or non-performance of any representation,
              warranty, covenant or agreement made or obligation to be performed
              by You pursuant to these Terms. Further, You agree to hold Company
              harmless against any claims made by any third party due to, or
              arising out of, or in connection with, Your use of the Website,
              any claim that Your material caused damage to a third party, Your
              violation of the Terms, or Your violation of any rights of
              another, including any intellectual property rights.
              Notwithstanding anything to contrary, Company's entire liability
              to You under this Terms or otherwise shall be to the extent of
              refund of the money charged from You for any specific voucher or
              Product or service, under which the unlikely liability arises. In
              no event shall Company, its officers, directors, employees,
              partners or suppliers be liable to You, the vendor or any third
              party for any special, incidental, indirect, consequential or
              punitive damages whatsoever, including those resulting from loss
              of use, data or profits, whether or not foreseeable or whether or
              not Company has been advised of the possibility of such damages,
              or based on any theory of liability, including breach of contract
              or warranty, negligence or other tortious action, or any other
              claim arising out of or in connection with Your use of or access
              to the Website, services or materials.
            </p>
            <p>
              Company is not responsible for any non-performance or breach of
              any contract entered into between Buyers and Sellers. Company
              cannot and does not guarantee that the concerned Buyers and/or
              Sellers will perform any transactions that are entered into on the
              Website. Company shall not and is not required to mediate or
              resolve any dispute or disagreement between Buyers and Sellers.
              Company does not, at any point of time during any transaction
              between Buyer and Seller on the Website. come into or take
              possession of any of the products or services offered by Seller
              nor does it at any point gain title to or have any rights or
              claims over the products or services offered by Seller to Buyer.
            </p>
            <p>
              At no time shall Company hold any right, title or interest over
              the products nor shall Company have any obligations or liabilities
              in respect of such contract entered into between Buyers and
              Sellers. Company is not responsible for any unsatisfactory or
              delayed performance of services or damages or delays as a result
              of products which are out of stock, unavailable or back ordered.
              The limitations and exclusions in this section apply to the
              maximum extent permitted by applicable law.
            </p>
          </li>
          <li>
            VIOLATION OF TERMS
            <p>
              You agree that Company may, in its sole discretion and without
              prior notice, terminate Your access to the Website and block Your
              future access to the Website, if Company determines that You have
              violated these Terms or Additional Terms. You also agree that any
              violation by You of these Terms will constitute an unlawful and
              unfair business practice, and will cause irreparable harm to
              Company, for which monetary damages would be inadequate, and You
              consent to Company obtaining any injunctive or equitable relief
              that Company deems necessary or appropriate in such circumstances.
              These remedies are in addition to any other remedies Company may
              have at law or in equity.
            </p>
            <p>
              You agree that Company may, in its sole discretion, and without
              prior notice, terminate Your access to the Website, for cause,
              which includes (but is not limited to): (1) requests by law
              enforcement or other government agencies; (2) a request by You
              (self-initiated account deletions); (3) discontinuance or material
              modification of the Website or any service offered on or through
              the Website; or unexpected technical issues or problems. If
              Company does take any legal action against You as a result of Your
              violation of these Terms, Company will be entitled to recover from
              You, and You agree to pay, all reasonable attorneys' fees and
              costs of such action, in addition to any other relief granted to
              Company.
            </p>
          </li>
          <li>
            TERMINATION
            <p>
              The Terms will continue to apply until terminated by either You or
              Company as set forth below. If You want to terminate Your
              agreement with Company, You may do so by{" "}
            </p>
            <ol type="i">
              <li>not accessing the Website; or </li>
              <li>
                closing Your accounts for all of the services that You use,
                where Company has made this option available to You.
              </li>
            </ol>
            <p>
              Company may, at any time, with or without notice, terminate the
              Terms (or portion thereof, such as any individual Additional
              Terms) with You if:
            </p>
            <ul>
              <li>
                You breach any of the provisions of the Terms, the Privacy
                Policy or any other terms, conditions, or policies that may be
                applicable to You from time to time (or have acted in a manner
                that clearly shows that You do not intend to, or are unable to,
                comply with the same);
              </li>
              <li>
                Company is required to do so by law (for example, where the
                provision of the services hereunder, to You is, or becomes,
                unlawful);
              </li>
              <li>
                The provision of the services to You, by Company is, in
                Company's opinion, no longer commercially viable;
              </li>
              <li>
                Company has elected to discontinue, with or without reason,
                access to the Website, the services (or any part thereof); or
                Company may also terminate or suspend all or a portion of Your
                account or access to the services with or without reason. Except
                as may be set forth in any Additional Terms applicable to a
                particular service, termination of Your Account may include: (i)
                removal of access to all offerings within the Website or with
                respect to the services; (ii) deletion of Your materials and
                Account Information, including Your personal information, log-in
                ID and password, and all related information, files and
                materials associated with or inside Your Account (or any part
                thereof); and (iii) barring of further use of the Services. You
                agree that all terminations shall be made in Company's sole
                discretion and that Company shall not be liable to You or any
                third party for any termination of Your Account (and
                accompanying deletion of Your Account Information), or Your
                access to the Website and the services offered thereunder.
              </li>
            </ul>
            <p>
              Notwithstanding the foregoing, these Terms will survive
              indefinitely unless and until Company chooses to terminate them.
              If You or Company terminates Your use of the Website, Company may
              delete any content or any other materials relating to Your use of
              the Website and Company will have no liability to You or any third
              party for doing so.
            </p>
          </li>
          <li>
            GOVERNING LAW
            <p>
              These Terms and all transactions entered into on or through the
              Website and the relationship between You and Company shall be
              governed in accordance with the laws of India without reference to
              conflict of laws principles.
            </p>
            <p>
              You agree that all claims, differences and disputes arising under
              or in connection with or in relation hereto the Website, the Terms
              or any transactions entered into on or through the Website or the
              relationship between You and Company shall be subject to the
              exclusive jurisdiction of the courts at Mumbai, India and You
              hereby accede to and accept the jurisdiction of such courts.
            </p>
          </li>
          <li>
            REPORT ABUSE
            <p>
              In the event You come across any abuse or violation of these Terms
              or if You become aware of any objectionable content on the
              Website, please report to Company’s customer support team.
            </p>
          </li>
          <li>
            PRIVACY POLICY
            <p>
              Company views the protection of Your privacy and information as a
              very important principle. We store and process Your Account
              Information including any sensitive personal / financial
              information collected (as defined under the Information Technology
              Act, 2000), if any, on computers that may be protected by physical
              as well as reasonable technological security measures and
              procedures in accordance with Information Technology Act 2000 and
              Rules there under. Company’s current Privacy Policy is available
              at www.alliswell.app/privacy-policy. If You object to Your
              Information being transferred or used in this way, please do not
              use Website. Company will share / sell / transfer / license /
              covey some or all of your personal information with another
              business entity, should we (or our assets) plan to merge with or
              are acquired by that business entity, or re-organization,
              amalgamation, restructuring of business or for any other reason
              whatsoever. Should such a transaction or situation occur, the
              other business entity or the new combined entity will be required
              to follow the privacy policy with respect to Your personal
              information. Once You provide Your information to us, You provide
              such information to Company and affiliates of Company and such
              Company and its affiliate may use such information to provide You
              various services with respect to Your transaction, whether such
              transaction are conducted on alliswell.app/or with third party
              merchant's or third party merchant's website. The User hereby
              consents, expresses and agrees that he/she has read and fully
              understands the Privacy Policy of Company in respect of the
              Website. You further consent that the terms and contents of such
              Privacy Policy are acceptable to You.
            </p>
          </li>
          <li>
            COMMUNICATIONS
            <p>
              You hereby expressly agree to receive communications by way of
              SMS, e-mails from Company, phone calls relating to the Products
              offered through the Website. A User can unsubscribe / opt-out from
              receiving communications from Company through SMS and e-mail
              anytime by:
            </p>
            <ul>
              <li>
                Visiting www.alliswell.app and unsubscribe from messages/ SMS
              </li>
              <li>
                Newsletters sent daily at the registered email address and by
                clicking on the unsubscribe option attached at the bottom of
                newsletter received through e-mail
                <br />
              </li>
            </ul>
          </li>
          <li>
            GENERAL PROVISIONS
            <p>
              Notice: All notices of Company will be served by email or by
              general notification on the Website. Any notice provided to
              Company pursuant to the Terms should be sent to
              contact@alliswell.app
            </p>
            <p>
              Assignment: You cannot assign or otherwise transfer the Terms, or
              any rights granted hereunder to any third party. Company's rights
              under the Terms are freely transferable by Company to any third
              parties without the requirement of seeking Your consent.
            </p>
            <p>
              Severability: If, for any reason, a court of competent
              jurisdiction finds any provision of these Terms, or portion
              thereof, to be unenforceable, that provision shall be enforced to
              the maximum extent permissible so as to give effect to the intent
              of the parties as reflected by that provision, and the remainder
              of the Terms shall continue in full force and effect.
            </p>
            <p>
              Waiver: Any failure by Company to enforce or exercise any
              provision of the Terms, or any related right, shall not constitute
              a waiver by Company of that provision or right.
            </p>
            <h3>Products</h3>
            <p>
              We maintain strict quality controls on all our partner retailers,
              so that you always get standard quality products.
            </p>
            <h3>Secure Payment</h3>
            <p>100% secure and trusted payment protection</p>
            <h3>Easy Return</h3>
            <p>
              We have a new and dynamic return window policy for medicines and
              healthcare items. Please refer Return Policy section for more
              details.
            </p>
          </li>
        </ol>
      </div>
    </main>
  );
}

export default TermsAndConditions;
